# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://blog.ztap.net
# title: Living as a Sojourner
subtitle: A place to trace my steps.
author: Hank Bao
simple_search: https://google.com/search

# Default extension for new posts and pages
post_ext: md
page_ext: md

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: hankbao
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: hankbao
twitter_tweet_count: 7
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
#google_plus_one: true
#google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
#googleplus_user: '110796053738665792614'
#googleplus_hidden: true
#googleplus_image_size: 32

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: blogsteps
disqus_show_comment_count: false
disqus_developer: 0

# Google Analytics
google_analytics_tracking_id: UA-37834364-1

# Facebook Like
facebook_like: true
